FROM php:7.4-fpm

# Set Environment Variables
ENV DEBIAN_FRONTEND=noninteractive

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

###########################################################################
# Install PHP extensions
###########################################################################

RUN install-php-extensions @fix_letsencrypt @composer \
    bcmath \
    event \
    intl \
    imagick \
    gd \
    gettext \
    mcrypt \
    mysqli \
    pdo_mysql \
    pcntl \
    redis \
    sockets \
    swoole \
    zip

###########################################################################
# PHP Basic Config
###########################################################################

COPY ./ini/php7.4.ini /usr/local/etc/php/php.ini
COPY ./custom.ini /usr/local/etc/php/conf.d
COPY ./custom.pool.conf /usr/local/etc/php-fpm.d/

###########################################################################
# Set Timezone
###########################################################################

ARG TZ=Asia/Shanghai
ENV TZ=${TZ}
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

###########################################################################
# xlswriter:
###########################################################################

ARG INSTALL_XLSWRITER=true
RUN set -eux; \
    if [ ${INSTALL_XLSWRITER} = true ]; then \
      # Install Php xlswriter Extension \
      if [ $(php -r "echo PHP_MAJOR_VERSION;") != "5" ]; then \
          install-php-extensions xlswriter  && \
          php -m | grep -q 'xlswriter'; \
      else \
          echo "PHP Extension for xlswriter is not supported for PHP 5.0";\
      fi \
    ;fi

