FROM php:7.3-fpm

# Set Environment Variables
ENV DEBIAN_FRONTEND=noninteractive

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

###########################################################################
# Install PHP extensions
###########################################################################

RUN install-php-extensions @fix_letsencrypt @composer \
    bcmath \
    event \
    intl \
    imagick \
    gd \
    gettext \
    mcrypt \
    mysqli \
    pdo_mysql \
    pcntl \
    redis \
    sockets \
    zip

###########################################################################
# PHP Basic Config
###########################################################################

RUN cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini && \
	sed -i 's/post_max_size =.*/post_max_size = 50M/g' /usr/local/etc/php/php.ini  && \
	sed -i 's/upload_max_filesize =.*/upload_max_filesize = 50M/g' /usr/local/etc/php/php.ini  && \
	sed -i 's/;date.timezone =.*/date.timezone = PRC/g' /usr/local/etc/php/php.ini  && \
	sed -i 's/short_open_tag =.*/short_open_tag = On/g' /usr/local/etc/php/php.ini  && \
	sed -i 's/;cgi.fix_pathinfo=.*/cgi.fix_pathinfo=1/g' /usr/local/etc/php/php.ini  && \
	sed -i 's/max_execution_time =.*/max_execution_time = 300/g' /usr/local/etc/php/php.ini

COPY ./www.conf /usr/local/etc/php-fpm.d/www.conf

###########################################################################
# Set Timezone
###########################################################################

ARG TZ=Asia/Shanghai
ENV TZ=${TZ}
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

###########################################################################
# xlswriter:
###########################################################################

ARG INSTALL_XLSWRITER=true
RUN set -eux; \
    if [ ${INSTALL_XLSWRITER} = true ]; then \
      # Install Php xlswriter Extension \
      if [ $(php -r "echo PHP_MAJOR_VERSION;") != "5" ]; then \
          install-php-extensions xlswriter  && \
          php -m | grep -q 'xlswriter'; \
      else \
          echo "PHP Extension for xlswriter is not supported for PHP 5.0";\
      fi \
    ;fi

